index:
    path: /
    controller: App\Controller\IndexController::index

register_confirm:
    path: /register/confirm/{token}
    controller: App\Controller\Auth\RegisterController::confirm

password_reset:
    path: /password/reset
    controller: App\Controller\Auth\PasswordResetController::reset